/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Query: {};
  Server: { // root type
    admin: string; // String!
    createdAt: string; // String!
    gif?: string | null; // String
    icon?: string | null; // String
    id: string; // String!
    name: string; // String!
  }
  User: { // root type
    createdAt: string; // String!
    id: string; // String!
    online: boolean; // Boolean!
    password: string; // String!
    profileUrl?: string | null; // String
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    addServer: NexusGenRootTypes['Server']; // Server!
    delServer: boolean; // Boolean!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
  }
  Query: { // field return type
    ok: boolean; // Boolean!
  }
  Server: { // field return type
    admin: string; // String!
    createdAt: string; // String!
    gif: string | null; // String
    icon: string | null; // String
    id: string; // String!
    members: NexusGenRootTypes['User'][]; // [User!]!
    name: string; // String!
  }
  User: { // field return type
    c_servers: NexusGenRootTypes['Server'][]; // [Server!]!
    createdAt: string; // String!
    id: string; // String!
    j_servers: NexusGenRootTypes['Server'][]; // [Server!]!
    online: boolean; // Boolean!
    password: string; // String!
    profileUrl: string | null; // String
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    addServer: 'Server'
    delServer: 'Boolean'
    login: 'AuthPayload'
    signup: 'AuthPayload'
  }
  Query: { // field return type name
    ok: 'Boolean'
  }
  Server: { // field return type name
    admin: 'String'
    createdAt: 'String'
    gif: 'String'
    icon: 'String'
    id: 'String'
    members: 'User'
    name: 'String'
  }
  User: { // field return type name
    c_servers: 'Server'
    createdAt: 'String'
    id: 'String'
    j_servers: 'Server'
    online: 'Boolean'
    password: 'String'
    profileUrl: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addServer: { // args
      gif?: string | null; // String
      icon?: string | null; // String
      name: string; // String!
      userId: string; // String!
    }
    delServer: { // args
      serverId: string; // String!
      userId: string; // String!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    signup: { // args
      password: string; // String!
      profileUrl?: string | null; // String
      username: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}